### ISSUE TITLE
Max requests queued per destination 1024 exceeded for HttpDestination

### ISSUE THREAD

**Issue by patpatpat123** [jetty-project/jetty-reactive-httpclient#226]
Hello team,

I would like to leverage reactive jetty http client in order to send as much request as possible in parallel.

However, when the load is climbing, I am always facing this issue:

```
Caused by: java.util.concurrent.RejectedExecutionException: Max requests queued per destination 1024 exceeded for HttpDestination[Origin@6ce2a85a[https://the-host.com:9200,tag=null,protocol=Protocol@7f4624a[proto=[http/1.1],nego=false]]]@12518d38,state=STARTED,queue=1024,pool=MultiplexConnectionPool@aa9711e[s=STARTED,c=5/64/64,a=59,i=0,q=1024,p=@6187c71b[inUse=59,size=64,max=64,closed=false]],stale=false,idle=-1
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:332)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:304)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:591)
	at org.eclipse.jetty.client.HttpRequest.sendAsync(HttpRequest.java:819)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:807)
	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.send(ResponseListenerProcessor.java:169)
	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onRequest(ResponseListenerProcessor.java:155)
	at org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.request(AbstractSinglePublisher.java:90)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134)
	at org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.subscribe(AbstractSinglePublisher.java:62)
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:71)

```

May I ask how to bump this number from 1024 to something higher, how to configure this number please?

Thank you

**Comment by sbordet** [comment]
Configure `HttpClient` like this:

`httpClient.setMaxRequestsQueuedPerDestination(<large number>)`

**Comment by patpatpat123** [comment]
Thank you @sbordet , closing
